// KG: sprint5C-editor-wasm-ui-2026-04-15
// Editor page load — passes URL params (peerId, mock) to page.

// $types is generated by SvelteKit at build time — use a local shim when unavailable.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const load = ({ url }: { url: URL }) => {
  const peerId = parseInt(url.searchParams.get('peerId') ?? '1', 10);
  const mock = url.searchParams.get('mock') === '1';
  return { peerId, mock };
};
